#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  6 16:11:35 2024

@author: admin
"""

import os

from boolean_parser import parse
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import SubElement
from xml.etree.ElementTree import ElementTree


table=[
    'model_result'
]

cond_map={
    "<": "LessThen",
    "<=": "LessThenEquals",
    ">": "GreaterThen",
    ">=": "GreaterThenEquals",
    "==": "Equals",
}


def GetRulesMapFromFile(files):
    table_map={}
    rules_map={}
    label_map={}
    type_map={}
    for file in files:
        tree=ElementTree(file=file)
        root=tree.getroot()
        for category in root.iter('category'):
            table_name=category.attrib['name']
            if table_name not in table:
                continue
            for elem in category.iter('var'):
                name=elem.attrib['name']
                label=elem.attrib['label']
                types=elem.attrib['type']
                lower_name=name.lower()
                table_map[lower_name]=table_name
                rules_map[lower_name]=name
                label_map[lower_name]=label
                type_map[lower_name]=types
    return table_map, rules_map, label_map, type_map


def GenIfBranch(parent, logicop, conditions, reloan_type,
                reloan_type_value, table_map, rules_map, label_map, type_map, black, black_list):
    black=black.strip()
    if_con_branch=SubElement(parent, 'if')
    if logicop == "and":
        cond_element=SubElement(if_con_branch, "and")
    elif logicop == "or":
        cond_element=SubElement(if_con_branch, "or")
    else:
        assert False, f'unsupport op: {logicop}'
    atom=SubElement(cond_element, "atom", op="Equals")
    left_attrs={
        "var-category": "参数",
        "var": 'is_firstloan_group',
        "var-label": "firstloan_group",
        "datatype": "Integer",
        "type": "parameter",
    }
    left=SubElement(atom, "left", attrib=left_attrs)
    value_attr={
        "content": reloan_type_value,
        "type": "Input",
    }
    value=SubElement(atom, "value", attrib=value_attr)

    if black == '300':
        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black3" % reloan_type_value,
            "var-label": "firstloan_group%s_black3" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '200':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black2" % reloan_type_value,
            "var-label": "firstloan_group%s_black2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

    elif black == '100':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black" % reloan_type_value,
            "var-label": "firstloan_group%s_black" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

    elif black == '1':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '2':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white2" % reloan_type_value,
            "var-label": "firstloan_group%s_white2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '3':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white2" % reloan_type_value,
            "var-label": "firstloan_group%s_white2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white3" % reloan_type_value,
            "var-label": "firstloan_group%s_white3" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    else:
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '1' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white" % reloan_type_value,
                "var-label": "firstloan_group%s_white" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '2' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white2" % reloan_type_value,
                "var-label": "firstloan_group%s_white2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '3' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white3" % reloan_type_value,
                "var-label": "firstloan_group%s_white3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

    for cond in conditions:
        atom=SubElement(cond_element, "atom",
                          op=cond_map[cond.operator])
        cond_name=cond.name.replace('_', '').lower()

        left_attrs={
            "var-category": table_map[cond_name],
            "var": rules_map[cond_name],
            "var-label": label_map[cond_name],
            "datatype": type_map[cond_name],
            "type": "variable",
        }
        left=SubElement(atom, "left", attrib=left_attrs)

        value_attr={
            "content": cond.value,
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)


def GenTagBranch(parent, condition, reloan_type,
                reloan_type_value, table_map, rules_map, label_map, type_map, black, black_list):
    print(black)
    black=black.strip()

    if_con_branch=SubElement(parent, 'if')
    
    cond_element=SubElement(if_con_branch, "and")
    
    atom=SubElement(cond_element, "atom", op="Equals")
    left_attrs={
        "var-category": "参数",
        "var": 'is_firstloan_group',
        "var-label": "firstloan_group",
        "datatype": "Integer",
        "type": "parameter",
    }
    left=SubElement(atom, "left", attrib=left_attrs)
    value_attr={
        "content": reloan_type_value,
        "type": "Input",
    }
    value=SubElement(atom, "value", attrib=value_attr)

    if black == '300':
        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black3" % reloan_type_value,
            "var-label": "firstloan_group%s_black3" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '200':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black2" % reloan_type_value,
            "var-label": "firstloan_group%s_black2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

    elif black == '100':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_black" % reloan_type_value,
            "var-label": "firstloan_group%s_black" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

    elif black == '1':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '2':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white2" % reloan_type_value,
            "var-label": "firstloan_group%s_white2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    elif black == '3':
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white" % reloan_type_value,
            "var-label": "firstloan_group%s_white" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="NotIn")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white2" % reloan_type_value,
            "var-label": "firstloan_group%s_white2" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)

        atom=SubElement(cond_element, "atom", op="Equals")
        left_attrs={
            "var-category": "参数",
            "var": "is_firstloan_group%s_white3" % reloan_type_value,
            "var-label": "firstloan_group%s_white3" % reloan_type_value,
            "datatype": "Integer",
            "type": "parameter",
        }
        left=SubElement(atom, "left", attrib=left_attrs)
        value_attr={
            "content": '1',
            "type": "Input",
        }
        value=SubElement(atom, "value", attrib=value_attr)
    else:
        if '300' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black3" % reloan_type_value,
                "var-label": "firstloan_group%s_black3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '200' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black2" % reloan_type_value,
                "var-label": "firstloan_group%s_black2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '100' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_black" % reloan_type_value,
                "var-label": "firstloan_group%s_black" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '1' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white" % reloan_type_value,
                "var-label": "firstloan_group%s_white" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '2' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white2" % reloan_type_value,
                "var-label": "firstloan_group%s_white2" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)

        if '3' in black_list:
            atom=SubElement(cond_element, "atom", op="NotIn")
            left_attrs={
                "var-category": "参数",
                "var": "is_firstloan_group%s_white3" % reloan_type_value,
                "var-label": "firstloan_group%s_white3" % reloan_type_value,
                "datatype": "Integer",
                "type": "parameter",
            }
            left=SubElement(atom, "left", attrib=left_attrs)
            value_attr={
                "content": '1',
                "type": "Input",
            }
            value=SubElement(atom, "value", attrib=value_attr)
    
    atom=SubElement(cond_element, "atom",
                      op=cond_map[condition.operator])
    cond_name=condition.name.replace('_', '').lower()

    left_attrs={
        "var-category": table_map[cond_name],
        "var": rules_map[cond_name],
        "var-label": label_map[cond_name],
        "datatype": type_map[cond_name],
        "type": "variable",
    }
    left=SubElement(atom, "left", attrib=left_attrs)

    value_attr={
        "content": condition.value,
        "type": "Input",
    }
    value=SubElement(atom, "value", attrib=value_attr)


def GenThenBranch(parent, reloan_type_value, value: float, black_list:str):
    then_branch=SubElement(parent, "then")
    
    black_list=black_list.strip()
    print(black_list,  '--------')
    
    value_attr={
        "var-category": "参数",
        "var": "firstloan_model_score_%s" % reloan_type_value,
        "var-label": "firstloan_model_score_%s" % reloan_type_value,
        "datatype": "Double",
        "type": "parameter"
    }
    var_assign=SubElement(then_branch, "var-assign", attrib=value_attr)

    value_attr={
        "var-category": "参数",
        "var": "firstloan_model_score_%s" % reloan_type_value,
        "var-label": "firstloan_model_score_%s" % reloan_type_value,
        "datatype": "Double",
        "type": "Parameter"
    }
    xml_value=SubElement(var_assign, "value", attrib=value_attr)

    add_attr={
        "type": "Add"
    }
    sub_attr={
        "type": "Sub"
    }
    if value >= 0:
        com=SubElement(xml_value, "complex-arith", attrib=add_attr)
    else:
        com=SubElement(xml_value, "complex-arith", attrib=sub_attr)

    value_attr={
        "content": str(abs(value)),
        "type": "Input"
    }
    SubElement(com, "value", attrib=value_attr)
    else_branch=SubElement(parent, "else")
    
    
def GenElseBranch(parent, reloan_type_value, value: float):
    then_branch=SubElement(parent, "else")
    value_attr={
        "var-category": "参数",
        "var": "score_sec_rule_" + reloan_type_value,
        "var-label": "sec规则评分_" + reloan_type_value,
        "datatype": "Double",
        "type": "parameter"
    }
    var_assign=SubElement(then_branch, "var-assign", attrib=value_attr)

    value_attr={
        "var-category": "参数",
        "var": "score_sec_rule_" + reloan_type_value,
        "var-label": "sec规则评分_" + reloan_type_value,
        "datatype": "Double",
        "type": "Parameter"
    }
    xml_value=SubElement(var_assign, "value", attrib=value_attr)

    add_attr={
        "type": "Add"
    }
    sub_attr={
        "type": "Sub"
    }
    if value >= 0:
        com=SubElement(xml_value, "complex-arith", attrib=add_attr)
    else:
        com=SubElement(xml_value, "complex-arith", attrib=sub_attr)

    value_attr={
        "content": str(abs(value)),
        "type": "Input"
    }
    SubElement(com, "value", attrib=value_attr)


def ToXml(table_map, rules_map, label_map, type_map, rules_file):
    root=Element("rule-set")
    rema=SubElement(root, 'remark')
    rema.text='<![CDATA[]]>'

    # with open(rules_file) as f:
    if True:
        for data in rules_file.keys():
            reloan_type=0
            print(data)
            if data == 'is_list1_inner_d7':
                reloan_type='0'
            elif data == 'is_list2_inner_d7':
                reloan_type='2'
            elif data == 'is_list3_inner_d7':
                reloan_type='3'

            reloan_type_value=reloan_type

            reloan_type_dict=rules_file[data]
            # print('111', reloan_type_dict)
            reloan_type_list=[int(i) for i in list(reloan_type_dict.keys())]
            reloan_type_list.sort()
            # print('222', reloan_type_list)

            for i in reloan_type_list:
                group_list=[str(k) for k in reloan_type_list]
                models_dict=reloan_type_dict[str(i)]
                for j in models_dict.keys():
                    res_bin, res_score=models_dict[j][0], models_dict[j][1]
                    res_bin.sort(reverse=True)
                    res_score.sort(reverse=True)
                    # print(i, j, res_bin, res_score)

                    for m, n in enumerate(res_bin):
                        if m == 0:
                            rule=j+'>%d'%res_bin[m]
                        elif m == len(res_bin)-1:
                            rule=j + '<=%d' % res_bin[m]
                        else:
                            rule=j + '<=%d' % res_bin[m-1] + ' and ' + j + '>%d' % res_bin[m]
                        score=res_score[m]
                        # print(i, rule, score)

                        xml_rule=SubElement(root, 'rule', name="rule")
                        remark_branch=SubElement(xml_rule, 'remark')
                        remark_branch.text='<![CDATA[]]>'

                        ret=parse(rule)
                        # print(i, rule, score, ret)
                        if hasattr(ret, "logicop"):
                            logicop=ret.logicop
                            conditions=ret.conditions
                            GenIfBranch(xml_rule, logicop, conditions, reloan_type, reloan_type_value, table_map, rules_map, label_map, type_map, str(i), group_list)
                            GenThenBranch(xml_rule, reloan_type_value, score, str(i))
                        else:
                            GenTagBranch(xml_rule, ret, reloan_type, reloan_type_value, table_map, rules_map, label_map, type_map, str(i), group_list)
                            GenThenBranch(xml_rule, reloan_type_value, score, str(i))

    tree=ElementTree(root)
    print('111', tree)
    tree.write("./rule1.text", encoding='UTF-8', xml_declaration=True)

    with open("./rule1.text", encoding='UTF-8') as f:
        res=f.read()
        res=res.replace("&lt;", '<').replace("&gt;", '>')

    with open("./rule1_format.text", 'w', encoding='UTF-8') as f:
        f.write(res)
    os.remove("./rule1.text")


def main():
    # p1='../决策引擎-规则流解析/特征库_html/extra_特征库.html'
    # p2='../决策引擎-规则流解析/特征库_html/extension_特征库.html'
    p3 = '/Users/admin/Documents/首贷原订单交叉/0806首贷原订单交叉订单/approval_特征库.html'
    table_map, rules_map, label_map, type_map=GetRulesMapFromFile([p3])

    model_score1='''case
when pinjamaxgboost928dpd7noforeign>581 then 6
when pinjamaxgboost928dpd7noforeign>559 then 5
when pinjamaxgboost928dpd7noforeign>527 then 4
when pinjamaxgboost928dpd7noforeign>473 then 3
when pinjamaxgboost928dpd7noforeign>427 then 2
else 1 end as t928_l1,

case
when pinjamaxgboost947dpd0fororiginorder>508 then 7
when pinjamaxgboost947dpd0fororiginorder>493 then 6
when pinjamaxgboost947dpd0fororiginorder>451 then 5
when pinjamaxgboost947dpd0fororiginorder>395 then 4
when pinjamaxgboost947dpd0fororiginorder>365 then 3
when pinjamaxgboost947dpd0fororiginorder>349 then 2
else 1 end as t947d0_l1,

case
when pinjamaxgboost947dpd7fororiginorder>522 then 7
when pinjamaxgboost947dpd7fororiginorder>496 then 6
when pinjamaxgboost947dpd7fororiginorder>460 then 5
when pinjamaxgboost947dpd7fororiginorder>410 then 4
when pinjamaxgboost947dpd7fororiginorder>370 then 3
when pinjamaxgboost947dpd7fororiginorder>350 then 2
else 1 end as t947d7_l1,

case
when pinjamaxgboost942dpd7forcreditgroup>534 then 8
when pinjamaxgboost942dpd7forcreditgroup>525 then 7
when pinjamaxgboost942dpd7forcreditgroup>484 then 6
when pinjamaxgboost942dpd7forcreditgroup>415 then 5
when pinjamaxgboost942dpd7forcreditgroup>372 then 4
when pinjamaxgboost942dpd7forcreditgroup>343 then 3
when pinjamaxgboost942dpd7forcreditgroup>330 then 2
else 1 end as t942_l1,

case
when pinjamaxgboost936dpd7>542 then 6
when pinjamaxgboost936dpd7>523 then 5
when pinjamaxgboost936dpd7>447 then 4
when pinjamaxgboost936dpd7>338 then 3
when pinjamaxgboost936dpd7>247 then 2
else 1 end as t936_l1,

case
when pinjamaxgboost949dpd7main>551 then 8
when pinjamaxgboost949dpd7main>521 then 7
when pinjamaxgboost949dpd7main>494 then 6
when pinjamaxgboost949dpd7main>450 then 5
when pinjamaxgboost949dpd7main>407 then 4
when pinjamaxgboost949dpd7main>383 then 3
when pinjamaxgboost949dpd7main>359 then 2
else 1 end as t949d7_l1,

case
when tt13.pinjamaxgboost952dpd7forcrosse0>479 then 6
when tt13.pinjamaxgboost952dpd7forcrosse0>446 then 5
when tt13.pinjamaxgboost952dpd7forcrosse0>400 then 4
when tt13.pinjamaxgboost952dpd7forcrosse0>357 then 3
when tt13.pinjamaxgboost952dpd7forcrosse0>325 then 2
else 1 end as t952d7_l1,

case
when pinjamaxgboost954dpd7forcrosse12>489 then 7
when pinjamaxgboost954dpd7forcrosse12>481 then 6
when pinjamaxgboost954dpd7forcrosse12>459 then 5
when pinjamaxgboost954dpd7forcrosse12>445 then 4
when pinjamaxgboost954dpd7forcrosse12>431 then 3
when pinjamaxgboost954dpd7forcrosse12>414 then 2
else 1 end as t954d7_l1'''




    model_score2='''
case
when is_list1_inner_d7=100 and t928_l1>5 then 84.1
when is_list1_inner_d7=100 and t928_l1>3 then 78.05
when is_list1_inner_d7=100 then 71.79
when is_list1_inner_d7=1 and t928_l1>1 then 55.13
when is_list1_inner_d7=1 then 51.11
else 0 end as score_1_model1,

case
when is_list1_inner_d7=100 and t947d0_l1>6 then 79.9
when is_list1_inner_d7=100 and t947d0_l1>5 then 77.97
when is_list1_inner_d7=100 and t947d0_l1>3 then 74.1
when is_list1_inner_d7=100 and t947d0_l1>2 then 69.21
when is_list1_inner_d7=100 then 65.88
when is_list1_inner_d7=1 and t947d0_l1>6 then 84.66
when is_list1_inner_d7=1 and t947d0_l1>5 then 70.16
when is_list1_inner_d7=1 and t947d0_l1>3 then 44.73
when is_list1_inner_d7=1 and t947d0_l1>2 then 23.98
when is_list1_inner_d7=1 then -29.64
when is_list1_inner_d7=0 and t947d0_l1>6 then 96.08
when is_list1_inner_d7=0 and t947d0_l1>5 then 84.69
when is_list1_inner_d7=0 and t947d0_l1>3 then 71.4
when is_list1_inner_d7=0 and t947d0_l1>2 then 51.58
when is_list1_inner_d7=0 and t947d0_l1>1 then 33.8
when is_list1_inner_d7=0 then 3.71
else 0 end as score_1_model2,

case
when is_list1_inner_d7=100 and t947d7_l1>6 then 181.25
when is_list1_inner_d7=100 and t947d7_l1>5 then 92.54
when is_list1_inner_d7=100 and t947d7_l1>4 then 85.31
when is_list1_inner_d7=100 and t947d7_l1>3 then 71.6
when is_list1_inner_d7=100 and t947d7_l1>2 then 49.48
when is_list1_inner_d7=100 then 28.52
when is_list1_inner_d7=1 and t947d7_l1>6 then 69.94
when is_list1_inner_d7=1 and t947d7_l1>5 then 62.89
when is_list1_inner_d7=1 and t947d7_l1>4 then 49.47
when is_list1_inner_d7=1 and t947d7_l1>3 then 44.84
when is_list1_inner_d7=1 and t947d7_l1>2 then 22.14
when is_list1_inner_d7=1 then 8.9
when is_list1_inner_d7=0 and t947d7_l1>6 then 78.23
when is_list1_inner_d7=0 and t947d7_l1>3 then 73.45
when is_list1_inner_d7=0 and t947d7_l1>1 then 69.12
when is_list1_inner_d7=0 then 60.52
else 0 end as score_1_model3,

case
when is_list1_inner_d7=100 and t942_l1>6 then 87.03
when is_list1_inner_d7=100 and t942_l1>5 then 80.88
when is_list1_inner_d7=100 and t942_l1>4 then 74.92
when is_list1_inner_d7=100 and t942_l1>2 then 66.4
when is_list1_inner_d7=100 then 50.27
when is_list1_inner_d7=1 and t942_l1>7 then 102.72
when is_list1_inner_d7=1 and t942_l1>5 then 64.2
when is_list1_inner_d7=1 and t942_l1>2 then 48.11
when is_list1_inner_d7=1 then 19.24
when is_list1_inner_d7=0 and t942_l1>7 then 104.21
when is_list1_inner_d7=0 and t942_l1>6 then 83.46
when is_list1_inner_d7=0 and t942_l1>3 then 73.57
when is_list1_inner_d7=0 and t942_l1>1 then 58.64
when is_list1_inner_d7=0 then 38.44
else 0 end as score_1_model4,

case
when is_list1_inner_d7=100 and t949d7_l1>6 then 109.93
when is_list1_inner_d7=100 and t949d7_l1>5 then 99.03
when is_list1_inner_d7=100 and t949d7_l1>4 then 83.6
when is_list1_inner_d7=100 and t949d7_l1>3 then 70.28
when is_list1_inner_d7=100 and t949d7_l1>2 then 51.4
when is_list1_inner_d7=100 and t949d7_l1>1 then 39.85
when is_list1_inner_d7=100 then 27.34
when is_list1_inner_d7=1 and t949d7_l1>7 then 98.02
when is_list1_inner_d7=1 and t949d7_l1>6 then 83.64
when is_list1_inner_d7=1 and t949d7_l1>5 then 68.91
when is_list1_inner_d7=1 and t949d7_l1>4 then 43.29
when is_list1_inner_d7=1 and t949d7_l1>3 then 20.98
when is_list1_inner_d7=1 and t949d7_l1>2 then 10.19
when is_list1_inner_d7=1 then -64.28
when is_list1_inner_d7=0 and t949d7_l1>7 then 136.58
when is_list1_inner_d7=0 and t949d7_l1>6 then 119.76
when is_list1_inner_d7=0 and t949d7_l1>5 then 94.45
when is_list1_inner_d7=0 and t949d7_l1>4 then 71.58
when is_list1_inner_d7=0 and t949d7_l1>3 then 48.45
when is_list1_inner_d7=0 and t949d7_l1>2 then 19.45
when is_list1_inner_d7=0 and t949d7_l1>1 then -6.17
when is_list1_inner_d7=0 then -21.33
else 0 end as score_1_model5,

case
when is_list1_inner_d7=100 and t952d7_l1>4 then 82.44
when is_list1_inner_d7=100 and t952d7_l1>3 then 77.29
when is_list1_inner_d7=100 and t952d7_l1>2 then 72.49
when is_list1_inner_d7=100 and t952d7_l1>1 then 65.54
when is_list1_inner_d7=100 then 55.56
when is_list1_inner_d7=1 and t952d7_l1>5 then 66.72
when is_list1_inner_d7=1 and t952d7_l1>1 then 54.39
when is_list1_inner_d7=1 then 35.77
when is_list1_inner_d7=0 and t952d7_l1>5 then 86.05
when is_list1_inner_d7=0 and t952d7_l1>4 then 81.87
when is_list1_inner_d7=0 and t952d7_l1>2 then 72.21
when is_list1_inner_d7=0 and t952d7_l1>1 then 60.67
when is_list1_inner_d7=0 then 39.99
else 0 end as score_1_model6,

case
when is_list1_inner_d7=1 and t936_l1>5 then 66.36
when is_list1_inner_d7=1 and t936_l1>4 then 61.47
when is_list1_inner_d7=1 and t936_l1>2 then 51.56
when is_list1_inner_d7=1 then 44.13
else 0 end as score_1_model7,

case
when is_list1_inner_d7=1 and t954d7_l1>5 then 70.93
when is_list1_inner_d7=1 and t954d7_l1>3 then 57.1
when is_list1_inner_d7=1 and t954d7_l1>2 then 39.84
when is_list1_inner_d7=1 and t954d7_l1>1 then 32.75
when is_list1_inner_d7=1 then 13.87
when is_list1_inner_d7=0 and t954d7_l1>6 then 79.76
when is_list1_inner_d7=0 and t954d7_l1>1 then 73.4
when is_list1_inner_d7=0 then 69.59
else 0 end as score_1_model8
'''
    model_bin_dict={}
    score1_list=model_score1.split('\n\n')
    print(score1_list)
    for i in score1_list:
        bin_list=[]
        bin_name=''
        bin_key=''
        i_list=i.replace(',', '').replace('case', '').strip().split('\n')
        for j in i_list:
            if 'when' in j:
                inequation=j.split(' ')[1]
                if not bin_name:
                    bin_name=inequation.split('>')[0]
                bin_list.append(int(inequation.split('>')[1]))
            else:
                bin_key=j.split(' ')[-1]
        bin_list.sort()
        model_bin_dict[bin_key]=[bin_name] + bin_list
    print(model_bin_dict)

    model_bin_dict_2={}
    score2_list=model_score2.split('\n\n')
    for i in score2_list:
        bin_value=0
        bin_score=0
        bin_key=''
        bin_type=''
        bin_name=''
        i_list=i.replace(',', '').replace('case', '').strip().split('\n')

        for j in i_list:
            # print(j)
            if 'when' in j and 'and' in j:
                inequation0=j.strip().split(' ')[1]
                inequation1=j.strip().split(' ')[3]
                bin_score=float(j.strip().split(' ')[-1])

                bin_key=inequation0.split('=')[0]
                bin_type=inequation0.split('=')[1]
                bin_name=inequation1.split('>')[0]
                bin_value=int(inequation1.split('>')[1])
            elif 'when' in j and 'and' not in j:
                inequation0=j.strip().split(' ')[1]
                bin_score=float(j.strip().split(' ')[-1])

                bin_key=inequation0.split('=')[0]
                bin_type=inequation0.split('=')[1]
            else:
                continue

            # print([bin_key,bin_type,bin_name,bin_value])
            tmp1=model_bin_dict_2.get(bin_key, {})
            tmp2=tmp1.get(bin_type, {})
            tmp3=tmp2.get(model_bin_dict[bin_name][0], [])

            if not tmp3:
                tmp3=[[model_bin_dict[bin_name][bin_value]], [bin_score]]
                tmp2[model_bin_dict[bin_name][0]]=tmp3
                tmp1[bin_type]=tmp2
                model_bin_dict_2[bin_key]=tmp1
            else:
                t1, t2=tmp3[0], tmp3[1]
                t1.append(model_bin_dict[bin_name][bin_value])
                t2.append(bin_score)
                t1.sort()
                t2.sort()
                tmp3=[t1, t2]
                tmp2[model_bin_dict[bin_name][0]]=tmp3
                tmp1[bin_type]=tmp2
                model_bin_dict_2[bin_key]=tmp1
    print(model_bin_dict_2)

    print(table_map)
    # print(rules_map)
    # print(label_map)
    # print(type_map)
    ToXml(table_map, rules_map, label_map, type_map, model_bin_dict_2)


if __name__ == "__main__":
    main()
